default_config:
  unit_system: imperial 

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  name: Home
  time_zone: America/New_York
  latitude: 32.7177 
  longitude: -80.12916
  elevation: 6 
  customize: !include customize.yaml

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 1000

dyson:
  username: !secret dyson_username 
  password: !secret dyson_password
  language: GB 
  devices:
    - device_id: !secret dyson_device_id 
      device_ip: 10.0.60.17

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
device_tracker: !include device_tracker.yaml

webostv:
  - host: 10.0.60.16
    name: Living Room TV
  - host: 10.0.60.15
    name: Man Cave TV

samsungtv:
  - host: 10.0.60.14
    name: Master Bedroom TV

media_player:

notify:
