- platform: template
  sensors:
     garage_entry_door:
       friendly_name: 'Garage Entry Door'
       value_template: >-
         {%- if is_state("sensor.vision_zd2105us5_recessed_doorwindow_sensor_alarm_level", "255") -%}
         open
         {%- else -%}
         closed
         {%- endif -%}
       icon_template: >-
         {%- if is_state("sensor.vision_zd2105us5_recessed_doorwindow_sensor_alarm_level", "255") -%} 
         mdi:door-open 
         {%- else -%}
         mdi:door-closed
         {%- endif -%}
- platform: template
  sensors:
     batt_garage_entry_door:
       friendly_name: 'Garage Entry Door Battery'
       unit_of_measurement: '%'
       value_template: "{{ state_attr('zwave.vision_security_zd2105us_5_recessed_door_window_sensor','attributes.battery_level')|int }}" 
       device_class: battery
- platform: template
  sensors:
     driveway_sensor:
       friendly_name: 'Driveway Motion Sensor'
       value_template: >-
         {%- if is_state("sensor.ecolink_doorwindow_sensor_access_control", "23") -%}
         open
         {%- else -%}
         closed
         {%- endif -%}
- platform: template
  sensors:                                                                                                                   
     batt_driveway_sensor:                                                                                                  
       friendly_name: 'Driveway Motion Sensor Battery'                                                                             
       unit_of_measurement: '%'  
       value_template: "{{ states.zwave.ecolink_door_window_sensor.attributes.battery_level }}"
       device_class: battery
